# Generated by Django 5.1.6 on 2025-02-22 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField()),
                ('num_columns', models.IntegerField()),
                ('num_rows', models.IntegerField()),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
