# Generated by Django 5.1.6 on 2025-02-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_querycache'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='table_name',
            field=models.CharField(default='default_table_name', max_length=255),
        ),
    ]
