# Generated by Django 5.1.6 on 2025-02-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='table_name',
            field=models.CharField(max_length=255),
        ),
    ]
