# Generated by Django 5.1.6 on 2025-02-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_report_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='table_name',
        ),
        migrations.DeleteModel(
            name='QueryCache',
        ),
    ]
