# Generated by Django 5.1.6 on 2025-03-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_report_table_name_delete_querycache'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
